In [1]:
import pandas as pd

In [2]:
# Creating a dataframe to read the json file that includes the comments for each individual
df1 = pd.read_json('wells_final.json')

In [3]:
# Printing the dataframe
df1

,rating,employee_type,review,date_position,pros,cons
0,"[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, ...","[Current Employee, more than 1 year, Current E...","[Great place for work & culture, Pros and some...","[Nov 25, 2021 - Treasury Management Sales Anal...",[Great management\r\nPlenty of PTO\r\nTons of ...,"[Intense schedule sometimes due to turnover, T..."
1,"[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, ...","[Current Employee, more than 1 year, Current E...","[Great place for work & culture, Pros and some...","[Nov 25, 2021 - Treasury Management Sales Anal...",[Great management\r\nPlenty of PTO\r\nTons of ...,"[Intense schedule sometimes due to turnover, T..."
2,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[Current Employee, Former Employee, Current Em...","[Working at Wellsfargo Auto, Teller review, Gr...","[Nov 23, 2021 - Customer Support Specialist, N...",[Working at wells fargo auto was a positive ex...,"[Because I was a temporary employee, I had les..."
3,"[4.0, 5.0, 4.0, 4.0, 4.0, 4.0, 4.0, 5.0, 4.0, ...","[Former Employee, Former Employee, more than 5...","[Salary, Good place, Large organization with o...","[Nov 23, 2021 - Anonymous Employee, Nov 21, 20...","[Have good opportunities,you can switch betwee...","[Management is not great,they will not show to..."
4,"[5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[Current Employee, Current Employee, less than...","[fast, awesome!, Good company, Wells Fargo, Gr...","[Nov 19, 2021 - Programmer Analyst, Nov 19, 20...","[the process was easy and fast, Amazing team, ...","[I dont have any cons, so complaints in my exp..."
...,...,...,...,...,...,...
996,"[4.0, 4.0, 4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 5.0, ...","[Current Employee, more than 3 years, Current ...","[Great place to work at, Good starting pay, Yo...","[May 21, 2019 - Bank Teller, May 21, 2019 - Te...",[Flexible schedule.\r\nA lot of time off.\r\nG...,"[Low pay compared with other banks, None yet a..."
997,"[2.0, 2.0, 4.0, 4.0, 4.0, 3.0, 5.0, 1.0, 4.0, ...","[Former Employee, less than 1 year, Current Em...","[Sell your soul to open accounts, Meh, Good co...","[Jun 4, 2019 - Bank Teller, Jun 4, 2019 - Anon...",[-schedule is bank hours so night shifts or lo...,[-management expects you to get each and every...
998,"[5.0, 5.0, 4.0, 4.0, 5.0, 3.0, 3.0, 3.0, 5.0, ...","[Current Employee, more than 3 years, Current ...","[Advancement Opportunity, Great job, Teller, G...","[May 19, 2019 - Licensed Personal Banker, May ...","[Advancement opportunity, tuition reimbursemen...","[None that don’t exist in every company., Very..."
999,"[2.0, 3.0, 5.0, 5.0, 2.0, 3.0, 3.0, 3.0, 3.0, ...","[Former Employee, more than 8 years, Current E...","[Behind the curtain is a real mess, Opportunit...","[May 31, 2019 - Change Consultant, May 31, 201...","[Good pay, decent health insurance, good paid ...",[Lots of hidden politics and things hidden whe...
1000,"[5.0, 2.0, 1.0, 1.0, 1.0, 5.0, 4.0, 4.0, 4.0, ...","[Current Employee, more than 1 year, Current E...","[Great Company with Growth Opportunity, Factor...","[May 14, 2019 - Lead Teller, May 28, 2019 - Bu...","[Great Benefits, Culture, and growth opportuni...",[The sales goals of previous years hinder the ...

In [4]:
# Using pandas explode() function to split the list in cell elements into individual row element across each column category
# Use Pandas >= 0.25 version
df1 = df1.apply(pd.Series.explode).reset_index()
df1.head()

,index,rating,employee_type,review,date_position,pros,cons
0,0,5.0,"Current Employee, more than 1 year",Great place for work & culture,"Nov 25, 2021 - Treasury Management Sales Analyst",Great management\r\nPlenty of PTO\r\nTons of c...,Intense schedule sometimes due to turnover
1,0,4.0,"Current Employee, more than 3 years",Pros and some Cons,"Nov 25, 2021 - Business Initiatives Consultant...","Amazing Pay and Benefits, Great Accommodations...","Training has been non-existent for many of us,..."
2,0,5.0,Current Employee,good working environment,"Nov 24, 2021 - Sales Representative","Everyone is really friendly, work environment ...",can get a bit repetitive
3,0,5.0,Former Employee,Great company,"Nov 24, 2021 - Compliance Manager",great pay great hours great benefits,unfortunately laid off due to lack of funds
4,0,5.0,Current Employee,Wells Fargo,"Nov 24, 2021 - Recruiter",Good work life balance- paid time off,"Too big , when you have an issue it can take d..."

In [5]:
# Splitting the date_position colmun into two individual columns called "date" & "job title"
df1[['date','job title']] = df1['date_position'].str.split("-", n=1, expand=True)
df1.head()

,index,rating,employee_type,review,date_position,pros,cons,date,job title
0,0,5.0,"Current Employee, more than 1 year",Great place for work & culture,"Nov 25, 2021 - Treasury Management Sales Analyst",Great management\r\nPlenty of PTO\r\nTons of c...,Intense schedule sometimes due to turnover,"Nov 25, 2021",Treasury Management Sales Analyst
1,0,4.0,"Current Employee, more than 3 years",Pros and some Cons,"Nov 25, 2021 - Business Initiatives Consultant...","Amazing Pay and Benefits, Great Accommodations...","Training has been non-existent for many of us,...","Nov 25, 2021",Business Initiatives Consultant III
2,0,5.0,Current Employee,good working environment,"Nov 24, 2021 - Sales Representative","Everyone is really friendly, work environment ...",can get a bit repetitive,"Nov 24, 2021",Sales Representative
3,0,5.0,Former Employee,Great company,"Nov 24, 2021 - Compliance Manager",great pay great hours great benefits,unfortunately laid off due to lack of funds,"Nov 24, 2021",Compliance Manager
4,0,5.0,Current Employee,Wells Fargo,"Nov 24, 2021 - Recruiter",Good work life balance- paid time off,"Too big , when you have an issue it can take d...","Nov 24, 2021",Recruiter

In [6]:
# Checking the data type of each column using the .info() function
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          10001 non-null  int64
 1   rating         10000 non-null  object
 2   employee_type  10000 non-null  object
 3   review         10000 non-null  object
 4   date_position  10000 non-null  object
 5   pros           10000 non-null  object
 6   cons           10000 non-null  object
 7   date           10000 non-null  object
 8   job title      10000 non-null  object
dtypes: int64(1), object(8)
memory usage: 703.3+ KB

In [7]:
# Converting the "date" column datatype from object to date format 
df1['date'] = pd.to_datetime(df1['date'])

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          10001 non-null  int64
 1   rating         10000 non-null  object
 2   employee_type  10000 non-null  object
 3   review         10000 non-null  object
 4   date_position  10000 non-null  object
 5   pros           10000 non-null  object
 6   cons           10000 non-null  object
 7   date           10000 non-null  datetime64[ns]
 8   job title      10000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 703.3+ KB

In [9]:
# Printing dataframe
df1.head(10)

,index,rating,employee_type,review,date_position,pros,cons,date,job title
0,0,5.0,"Current Employee, more than 1 year",Great place for work & culture,"Nov 25, 2021 - Treasury Management Sales Analyst",Great management\r\nPlenty of PTO\r\nTons of c...,Intense schedule sometimes due to turnover,2021-11-25,Treasury Management Sales Analyst
1,0,4.0,"Current Employee, more than 3 years",Pros and some Cons,"Nov 25, 2021 - Business Initiatives Consultant...","Amazing Pay and Benefits, Great Accommodations...","Training has been non-existent for many of us,...",2021-11-25,Business Initiatives Consultant III
2,0,5.0,Current Employee,good working environment,"Nov 24, 2021 - Sales Representative","Everyone is really friendly, work environment ...",can get a bit repetitive,2021-11-24,Sales Representative
3,0,5.0,Former Employee,Great company,"Nov 24, 2021 - Compliance Manager",great pay great hours great benefits,unfortunately laid off due to lack of funds,2021-11-24,Compliance Manager
4,0,5.0,Current Employee,Wells Fargo,"Nov 24, 2021 - Recruiter",Good work life balance- paid time off,"Too big , when you have an issue it can take d...",2021-11-24,Recruiter
5,0,5.0,"Former Employee, more than 3 years",Good Bank to work for,"Nov 24, 2021 - Lead Teller/Supervisor",Customer Experience is the main priority,Hard to move up within the company,2021-11-24,Lead Teller/Supervisor
6,0,4.0,Former Employee,good,"Nov 24, 2021 - Bank Teller",working with a lot of different people,"easy to get fired, if you mess up.",2021-11-24,Bank Teller
7,0,4.0,Current Employee,Good Team,"Nov 25, 2021 - Anonymous Employee",Great teammates to work with,Restrictions for trading of stocks and derivat...,2021-11-25,Anonymous Employee
8,0,5.0,Former Employee,Teller Pay,"Nov 23, 2021 - Teller","Fair Pay, Good Vacation, Room to Grow",Very busy all the time,2021-11-23,Teller
9,0,5.0,"Former Employee, more than 1 year",good place to work,"Nov 23, 2021 - Personal Banker","Good environment, all employees are friendly.",have to meet Sales quotes,2021-11-23,Personal Banker

In [10]:
# Finding the number of unique element in the dataframe column
df1.nunique()

index            1001
rating              5
employee_type      14
review           5977
date_position    8554
pros             9669
cons             9750
date              921
job title        2069
dtype: int64

In [11]:
df1.columns

Index(['index', 'rating', 'employee_type', 'review', 'date_position', 'pros',
       'cons', 'date', 'job title'],
      dtype='object')

In [12]:
df1.reset_index(drop=True, inplace=True)

In [13]:
df1.columns

Index(['index', 'rating', 'employee_type', 'review', 'date_position', 'pros',
       'cons', 'date', 'job title'],
      dtype='object')

In [14]:
# Droping "index" column from the dataframe
df1 = df1.drop(['index'], axis=1)
df1.head()

,rating,employee_type,review,date_position,pros,cons,date,job title
0,5.0,"Current Employee, more than 1 year",Great place for work & culture,"Nov 25, 2021 - Treasury Management Sales Analyst",Great management\r\nPlenty of PTO\r\nTons of c...,Intense schedule sometimes due to turnover,2021-11-25,Treasury Management Sales Analyst
1,4.0,"Current Employee, more than 3 years",Pros and some Cons,"Nov 25, 2021 - Business Initiatives Consultant...","Amazing Pay and Benefits, Great Accommodations...","Training has been non-existent for many of us,...",2021-11-25,Business Initiatives Consultant III
2,5.0,Current Employee,good working environment,"Nov 24, 2021 - Sales Representative","Everyone is really friendly, work environment ...",can get a bit repetitive,2021-11-24,Sales Representative
3,5.0,Former Employee,Great company,"Nov 24, 2021 - Compliance Manager",great pay great hours great benefits,unfortunately laid off due to lack of funds,2021-11-24,Compliance Manager
4,5.0,Current Employee,Wells Fargo,"Nov 24, 2021 - Recruiter",Good work life balance- paid time off,"Too big , when you have an issue it can take d...",2021-11-24,Recruiter

## Data Consolidation

In [15]:
df1.dropna(inplace=True)

In [57]:
# Importing dataset using pd.read_csv

In [21]:
df1.head()

,rating,employee_type,review,pros,cons,date,job title
0,5.0,"Current Employee, more than 1 year",Great place for work & culture,Great management\r\nPlenty of PTO\r\nTons of c...,Intense schedule sometimes due to turnover,2021-11-25,Treasury Management Sales Analyst
1,4.0,"Current Employee, more than 3 years",Pros and some Cons,"Amazing Pay and Benefits, Great Accommodations...","Training has been non-existent for many of us,...",2021-11-25,Business Initiatives Consultant III
2,5.0,Current Employee,good working environment,"Everyone is really friendly, work environment ...",can get a bit repetitive,2021-11-24,Sales Representative
3,5.0,Former Employee,Great company,great pay great hours great benefits,unfortunately laid off due to lack of funds,2021-11-24,Compliance Manager
4,5.0,Current Employee,Wells Fargo,Good work life balance- paid time off,"Too big , when you have an issue it can take d...",2021-11-24,Recruiter

In [22]:
# df1 = df1.drop(['date_position'], axis=1)
# df1.head()

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 10000
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rating         10000 non-null  object
 1   employee_type  10000 non-null  object
 2   review         10000 non-null  object
 3   pros           10000 non-null  object
 4   cons           10000 non-null  object
 5   date           10000 non-null  datetime64[ns]
 6   job title      10000 non-null  object
dtypes: datetime64[ns](1), object(6)
memory usage: 625.0+ KB

In [24]:
df1.to_csv('wells_fargo_final.csv')